/*--------------------------------------------------------------------------------------
 *  Copyright 2025 Glass Devtools, Inc. All rights reserved.
 *  Licensed under the Apache License, Version 2.0. See LICENSE.txt for more information.
 *--------------------------------------------------------------------------------------*/

import { AgentRole, ProviderName } from '../../../../common/voidSettingsTypes.js';

// Agent execution status
export type AgentStatus = 'idle' | 'running' | 'completed' | 'error' | 'waiting' | 'awaiting_approval';

// Individual agent state in the conductor view
export interface AgentState {
	role: AgentRole;
	status: AgentStatus;
	provider: ProviderName;
	model: string;
	startTime: number | null;
	endTime: number | null;
	tokensUsed: number;
	summary: string;
	error: string | null;
	output: string; // markdown content generated by this agent (shown in approval panel)
}

// Metrics for the meta panel
export interface ConductorMetrics {
	totalTokens: number;
	estimatedCost: number;
	totalTime: number;
	successRate: number;
	agentCount: number;
	completedCount: number;
}

// Pipeline step configuration
export interface PipelineStep {
	id: string;
	role: AgentRole;
	provider: ProviderName;
	model: string;
	order: number;
}

// Thought tree node
export interface ThoughtNode {
	id: string;
	role: AgentRole;
	content: string;
	children: ThoughtNode[];
	status: AgentStatus;
	depth: number;
}

// Pipeline template
export interface PipelineTemplate {
	id: string;
	name: string;
	description: string;
	icon: string;
	steps: PipelineStep[];
}

// Conductor view tabs
export type ConductorTab = 'pipeline' | 'builder' | 'thoughts' | 'conductor';

// Agent strength tags
export interface AgentStrengthTag {
	label: string;
	color: string;
}

// Strength tags for known capabilities
export const agentStrengthTags: Record<AgentRole, AgentStrengthTag[]> = {
	leader: [
		{ label: 'Coordination', color: '#f59e0b' },
		{ label: 'Task Analysis', color: '#8b5cf6' },
	],
	coder: [
		{ label: 'Code Generation', color: '#3b82f6' },
		{ label: 'Debugging', color: '#ef4444' },
	],
	planner: [
		{ label: 'Architecture', color: '#10b981' },
		{ label: 'Strategy', color: '#6366f1' },
	],
	search: [
		{ label: 'Research', color: '#06b6d4' },
		{ label: 'Documentation', color: '#84cc16' },
	],
	research: [
		{ label: 'Deep Research', color: '#8b5cf6' },
		{ label: 'Analysis', color: '#06b6d4' },
	],
	design: [
		{ label: 'UI/UX', color: '#ec4899' },
		{ label: 'Visual Design', color: '#f97316' },
	],
	writing: [
		{ label: 'Content', color: '#14b8a6' },
		{ label: 'Documentation', color: '#84cc16' },
	],
	ideaman: [
		{ label: 'Ideation', color: '#eab308' },
		{ label: 'Brainstorming', color: '#f59e0b' },
	],
	filesearch: [
		{ label: 'File Lookup', color: '#0ea5e9' },
		{ label: 'Codebase', color: '#22c55e' },
	],
	image: [
		{ label: 'Image Gen', color: '#d946ef' },
		{ label: 'Visuals', color: '#f97316' },
	],
	review: [
		{ label: 'QA', color: '#ef4444' },
		{ label: 'Verification', color: '#10b981' },
	],
};

// Role display configuration
export const roleDisplayConfig: Record<AgentRole, { label: string; color: string; glowColor: string }> = {
	leader: { label: 'Leader', color: '#f59e0b', glowColor: 'rgba(245, 158, 11, 0.4)' },
	coder: { label: 'Coder', color: '#3b82f6', glowColor: 'rgba(59, 130, 246, 0.4)' },
	planner: { label: 'Planner', color: '#10b981', glowColor: 'rgba(16, 185, 129, 0.4)' },
	search: { label: 'Search', color: '#06b6d4', glowColor: 'rgba(6, 182, 212, 0.4)' },
	research: { label: 'Research', color: '#8b5cf6', glowColor: 'rgba(139, 92, 246, 0.4)' },
	design: { label: 'Designer', color: '#ec4899', glowColor: 'rgba(236, 72, 153, 0.4)' },
	writing: { label: 'Writer', color: '#14b8a6', glowColor: 'rgba(20, 184, 166, 0.4)' },
	ideaman: { label: 'Idea man', color: '#eab308', glowColor: 'rgba(234, 179, 8, 0.4)' },
	filesearch: { label: 'File Search', color: '#0ea5e9', glowColor: 'rgba(14, 165, 233, 0.4)' },
	image: { label: 'Image', color: '#d946ef', glowColor: 'rgba(217, 70, 239, 0.4)' },
	review: { label: 'Reviewer', color: '#ef4444', glowColor: 'rgba(239, 68, 68, 0.4)' },
};

// Default pipeline templates
export const defaultTemplates: PipelineTemplate[] = [
	{
		id: 'orchestra-flow',
		name: 'Orchestra Flow',
		description: 'Leader → (Ideaman, Search, Research) → (Designer, Image, Planner) → File Search → (Coder or Writer) → Reviewer',
		icon: 'Layers',
		steps: [
			{ id: '1', role: 'leader', provider: 'openAI', model: 'gpt-4o', order: 0 },
			{ id: '2', role: 'ideaman', provider: 'openAI', model: 'gpt-4o', order: 1 },
			{ id: '3', role: 'search', provider: 'openAI', model: 'gpt-4o', order: 2 },
			{ id: '4', role: 'research', provider: 'openAI', model: 'gpt-4o', order: 3 },
			{ id: '5', role: 'design', provider: 'gemini', model: 'gemini-2.0-flash', order: 4 },
			{ id: '6', role: 'image', provider: 'gemini', model: 'gemini-2.0-flash', order: 5 },
			{ id: '7', role: 'planner', provider: 'gemini', model: 'gemini-2.0-flash', order: 6 },
			{ id: '8', role: 'filesearch', provider: 'openAI', model: 'gpt-4o', order: 7 },
			{ id: '9', role: 'coder', provider: 'anthropic', model: 'claude-sonnet-4-20250514', order: 8 },
			{ id: '10', role: 'writing', provider: 'openAI', model: 'gpt-4o', order: 9 },
			{ id: '11', role: 'review', provider: 'anthropic', model: 'claude-sonnet-4-20250514', order: 10 },
		],
	},
	{
		id: 'web-article',
		name: 'Web Article Generation',
		description: 'Research, plan, write, and review web articles',
		icon: 'FileText',
		steps: [
			{ id: '1', role: 'leader', provider: 'openAI', model: 'gpt-4o', order: 0 },
			{ id: '2', role: 'search', provider: 'openAI', model: 'gpt-4o', order: 1 },
			{ id: '3', role: 'planner', provider: 'gemini', model: 'gemini-2.0-flash', order: 2 },
			{ id: '4', role: 'writing', provider: 'openAI', model: 'gpt-4o', order: 3 },
			{ id: '5', role: 'review', provider: 'anthropic', model: 'claude-sonnet-4-20250514', order: 4 },
		],
	},
	{
		id: 'app-dev',
		name: 'App Development',
		description: 'Plan, code, design, and review applications',
		icon: 'Code',
		steps: [
			{ id: '1', role: 'leader', provider: 'openAI', model: 'gpt-4o', order: 0 },
			{ id: '2', role: 'planner', provider: 'gemini', model: 'gemini-2.0-flash', order: 1 },
			{ id: '3', role: 'design', provider: 'gemini', model: 'gemini-2.0-flash', order: 2 },
			{ id: '4', role: 'coder', provider: 'anthropic', model: 'claude-sonnet-4-20250514', order: 3 },
			{ id: '5', role: 'review', provider: 'anthropic', model: 'claude-sonnet-4-20250514', order: 4 },
		],
	},
	{
		id: 'research',
		name: 'Research & Analysis',
		description: 'Search, analyze, and synthesize research findings',
		icon: 'Search',
		steps: [
			{ id: '1', role: 'leader', provider: 'openAI', model: 'gpt-4o', order: 0 },
			{ id: '2', role: 'search', provider: 'openAI', model: 'gpt-4o', order: 1 },
			{ id: '3', role: 'research', provider: 'openAI', model: 'gpt-4o', order: 2 },
			{ id: '4', role: 'planner', provider: 'gemini', model: 'gemini-2.0-flash', order: 3 },
		],
	},
];
